version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:mongodb
    environment:
      - ATLAS_URI=mongodb://admin:mongodb@mongodb:27017/employees
      - PORT=5050

  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: employees
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb-data:
  mongodb-config:
